### ISSUE TITLE
TODO:  API Calls

### ISSUE THREAD

**Issue by VoxLight** [VoxLight/E621.py#1]
<html>
<body>

- [ ] Search posts       -  /posts.json            -  GET
- [ ] Upload a new post  -  /uploads.json          -  POST
- [ ] Update a post      -  /posts/<Post_ID>.json  -  PATCH
- [ ] Search flags       -  /post_flags.json       -  GET
- [ ] Create a new flag  -  /post_flags.json       -  POST
- [ ] Vote on a post     -  /posts/<Post_ID>/votes.json  -  POST
- [ ] Favorite a post    -  /favorites.json        -  POST
- [ ] Delete a favorite  -  /favorites/<Post_ID>.json  -  DELETE
- [ ] Search notes       -  /notes.json            -  GET
- [ ] Create a new note  -  /notes.json            -  POST
- [ ] Update an existing note  -  /notes/<Note_ID>.json  -  PUT
- [ ] Delete a note      -  /notes/<Note_ID>.json  -  DELETE
- [ ] Revert a note to a previous version  -  /notes/<Note_ID>/revert.json                            -  PUT
- [ ] Search pools       -  /pools.json            -  GET
- [ ] Create a new pool  -  /pools.json            -  POST
- [ ] Update pool        -  /pools/<Pool_ID>.json  -  PUT
- [ ] Revert pool to some previous version  -  /pools/<Pool_ID>/revert.json                            -  PUT

</body>
</html>
